### ISSUE TITLE
Issues testing with the nuscenes mini : "This mmdetection3d version is not supported."

### ISSUE THREAD

**Issue by zarathacia** [ika-rwth-aachen/MultiCorrupt#10]
I am encountering the following error:

```
This mmdetection3d version is not supported.
```

**Details:**

This error occurs when I run the following command:

```bash
python3 converter/lidar_converter.py --corruption snow --root_folder /workspaces/MultiCorrupt/data/nuscenes/v1.0-mini --dst_folder /workspaces/multicorrupt/snow/3/ --severity 3 --n_cpus 64 --sweep true
```

**Environment:**
- Python version: python3
- OS: ubuntu 22.04

Do you have any recommendations on how to resolve this issue? Any guidance would be greatly appreciated.

Thank you!

**Comment by TillBeemelmanns** [comment]
I have not tested nuscenes mini. Can you please try to use the full nuscenes version ? 

I will be able to test/debug nuscenes mini earliest next week.

Best,
Till

**Comment by zarathacia** [comment]
The problem was with the file nuscenes_info_val.pkl. Changing it to the right format fixed the error. I tried the image converter, and it works well. The repo works with the mini version.
