### ISSUE TITLE
About Reproducing CMT

### ISSUE THREAD

**Issue by curiosity654** [ika-rwth-aachen/MultiCorrupt#11]
Hi! Thanks for the amazing project. I plan to work on your repo but before that, I met with some problem in reproducing Cross Modal Transformer. As the original repo seems slow to respond now, I come here for some guidance.

The problem is about the dbsample in CMT's codebase. I encounter image path missing problem on some instances. [This link](https://github.com/junjie18/CMT/issues/47) describes my problem and I'd like to know how you handle this?

For reference, I also found there's a [potential bug](https://github.com/junjie18/CMT/issues/75) that can cause more instances without image. Now I'm using this modification and rerunning the database creation.

Any help is appreciated!

**Comment by TillBeemelmanns** [comment]
Hi curiosity654,

please follow their website in generating the `.pkl` files for the db sampler. Seems like you are currently not using the correct `.pkl` file, possibly generated by a different framework or different version of mmdetection3d. 

However, this is not the matter of this repository. All information how to run CMT is available at their repository.

Best,
Till

**Comment by curiosity654** [comment]
Thank you so much! I have found my problem. I manually changed the image_path in the generated pkl to absolute path, so the filter of aug without image "if len(info['image_path']) > 0:" does not work. After changing back, the code runs without problem.
