### ISSUE TITLE
Estimated Generation Time

### ISSUE THREAD

**Issue by curiosity654** [ika-rwth-aachen/MultiCorrupt#12]
Hello, I find it's quite time consuming to generate data of LiDAR. Could you please provide the estimated preprocessing time (with cpu core number used) for reference? Thank you very much!

**Comment by curiosity654** [comment]
I found that only the snow corruption on LiDAR is very time consuming, other corruptions' preprocessing time is quite reasonable.

Here I list some data just for reference, I run on a HPC cluster and require 32 CPUs for each job.

- LIDAR snow 12h
- LIDAR fog 0.5 h
- LiDAR others takes less than 1 min
- Image snow 0.5 h
- Image fog 3h
- Image motion blur 1h

**Comment by TillBeemelmanns** [comment]
Thanks for reporting these numbers. I always used approx. 256 CPU cores, hence I did not had to wait too long for generating these numbers. But I can confirm, LIDAR snow takes the most time since the snowflakes are rendered in the 3D space. I will update the `README.md` accordingly soon.

**Comment by fdy61** [comment]
> Hello, I find it's quite time consuming to generate data of LiDAR. Could you please provide the estimated preprocessing time (with cpu core number used) for reference? Thank you very much!

Hello, I want to ask one question. Does the size of the snow point cloud files you generated fluctuate significantly? I've noticed that the point cloud file sizes range from tens to several hundred kilobytes

**Comment by TillBeemelmanns** [comment]
Yes, that is possible depending on the snowflakes being rendered into the scene. Some snow flakes occlude the LiDAR and hence many of the point in the point clouds are remove. This process is kind random which results in random file sizes for the point cloud for the snow corruption.

**Comment by TillBeemelmanns** [comment]
You can also see it in the visualization for snow: https://github.com/ika-rwth-aachen/MultiCorrupt/blob/main/assets/snow_2_front_camera_scene-0097_scene_animation.gif

**Comment by fdy61** [comment]
OK, thank you very much.
