### ISSUE TITLE
Error points generation in fog simulation

### ISSUE THREAD

**Issue by fdy61** [ika-rwth-aachen/MultiCorrupt#13]
I found that for the 5th point cloud in nuscenes_infos_val.pkl, after simulating fog, the point cloud gets concentrated along the diagonal, which is very strange. The pictures are below.
![image](https://github.com/user-attachments/assets/9d3ad1f3-d91a-4d62-ae75-6e583672304e)

In the 8th point cloud from nuscenes_infos_val.pkl, some point clouds are generated at a very far distance. The pictures are below.
![image](https://github.com/user-attachments/assets/1c13629a-3a4e-4037-8953-71bdc0dcf970)

I just checked and visualized the first few point clouds and noticed this issue. The later point clouds might also have the same problem.

**Comment by TillBeemelmanns** [comment]
Can you use identical scales (x,y,z) for all of your plots ? Seems it's just like a visualization issue ? Can you provide the number of points for the corrupted point clouds in both of your examples ?

**Comment by fdy61** [comment]
The number of the 5th point is 34752. The number of the 8th point is 34688

**Comment by TillBeemelmanns** [comment]
Okay, the number of points indicate that everything is okay and also that means it's very probably that there is just a visualization issue in your plots above.

**Comment by fdy61** [comment]
Ok, thank you for your reply.
