### ISSUE TITLE
Would you consider adding a dataset for rainy weather conditions?

### ISSUE THREAD

**Issue by Neko-coffee** [ika-rwth-aachen/MultiCorrupt#17]
Great work! I was wondering if you would consider adding a dataset for rainy weather conditions, as common weather-related corruptions typically include rain, snow, and fog.

**Comment by TillBeemelmanns** [comment]
Thanks for the question!

NuScenes naturally contains rainy scenes, hence I did not consider this weather condition separately. You can check out other repositories or iterate over the nuScenes scenes descriptions and check if they contain `rain`.

Here is also a list of rainy scenes, but I am not sure this list is fully correct.
https://github.com/ika-rwth-aachen/MultiCorrupt/blob/1f054edd20ebbf80080566fcae658a92b377df04/helper/nuscenes_split.py#L48


Best,
Till

**Comment by Neko-coffee** [comment]
Thank you for your quick response and detailed explanation! I understand that NuScenes already includes rainy scenes, which is indeed a very good reference. I also appreciate you providing the list of rainy scenes, and I will check it further and try to collect relevant data based on this information. Thanks again for your help!
