### ISSUE TITLE
Fewer generated foggy images in nuscenes-mini dataset

### ISSUE THREAD

**Issue by Neko-coffee** [ika-rwth-aachen/MultiCorrupt#6]
I followed the steps to generate foggy weather data using the nuscenes-mini dataset, but the number of generated images is significantly less than the original dataset. For example, the number of images in the CAM_BACK folder has decreased from 404 (original) to 81 (foggy). 
I would appreciate any insights or suggestions on why this might be happening and how I can resolve it. Thank you!

**Comment by TillBeemelmanns** [comment]
Hi,
two possible answers:

- Only images from the validation split are converted. Images from the training set are not considered. 
- For camera images, only the samples are converted, but not the sweep camera images

Bests,
Till

**Comment by Neko-coffee** [comment]
> Hi, two possible answers:
> 
> * Only images from the validation split are converted. Images from the training set are not considered.
> * For camera images, only the samples are converted, but not the sweep camera images
> 
> Bests, Till

Dear Till,

I'm a newbie with some basic questions, thanks for your patience! Based on your reply, does the image conversion depend on the file nuscenes_infos_val.pkl? Therefore, if I want to convert all the images, should I run the process again using nuscenes_infos_train.pkl? This way, I can convert all the images, or is there another method available?
